language: node_js
node_js:
- 12
before_deploy:
- yarn config set version-commit-hooks false
- yarn config set version-git-tag false
- yarn config set version-sign-git-tag false
- echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
- echo "@${NPM_LOGIN}:registry=https://registry.npmjs.org/" >> ~/.npmrc
deploy:
  provider: script
  script: yarn release
  on:
    branch: master
env:
  global:
  - secure: eY6oIHY5UJk9VXrd2KMUWWe11LUdFcm0JDJ0eO9kNam63z93ml3vSIDpT3OlmZFTkgIq/shF59/3ELRlfNX0KaVXyhgYrIowO1rUGGFnR39O2NPMJpK0bu8PQmNC1jxo4pfC2NW5uC4RT+T0VEkyFkS3FQH38rHsipUIxW4fRXpud1jyKYdB8joDnLsM2zOJcOtebcIuMgIHUSLwsreR0m74XxMLD0LgOaH88ED7kGL/Fl7Qh+GrMD7XRjat7GYk9gVk50+hLWSRF8WdKecysplWbwsa2xUBCSrz+xCdQQEABEVs9Ipi+cVaLOP3iEdqCFt//vTUDkOccX4UTeCJbzRj85tRQ8nKBoaksz1310y/QocntVEFwpuvwKJucaMj3DMaH/HYcKvvIicIrWf1YY0Y1Rny1lgWPYXzBFW1IxosXnGNOP1lG6idCXDME00kEp4R+UtQH4I9cE4IlhbSlO9cRAOd/58ZRY/ZK1fR20S1KnziCD6kkTfmmnBPbpBSjfqE3sjUowHOhzXYk558TOI7KJTAA6kXcSW/1aWzysl8VJ8FQiP2N1mr5YzypY2gUeIL4WeU53vE1fAtyJC2faYJiON3G5NIQTG6U9mJrUSeb9gNYkIh2l/94ouUJw8kFtOTSvVU8aNuiyFK1k5sj+RZKKC+YTojJfVPqXRdoCc=
  - secure: rENOsF0tzNDCcKyZgL42SrVuviH9phE9zU9Z3t7PfEBR0j1vddG407ktf4tKdNHWDUyXTC0mP42V0Igsbi7NhHCm7ZrSb96DDJgA7fyOX3/bb1iQJC2Il/+lRD38nbaquOujny4ZiX+/HhQ/UxmJgJfeyrPoZgSs1QmxoIAmo8QByNYsLn7OkaiVZypdq3U4dkkiyICxW8KryS89IZpkmhNRsPadxiW9HBIfrn7FpeRnXMxvrAlWQLXYa4ZfJxl7nTSd32hRohEvyLpBAOGUs8fDK53JxqaYf4kYE9eKJLZUEcpzXa67m2WFPFg8pF8mDBnnvGUbRWSZ1CQYtHyau+9Bt3ukg5We5TnFNrtOjg67ynPX8zEWIydcXs88xFuuQFijUlB8nantyYb9VnjatxO2W5YgDx9VJX9xp5+AXOAnPyl3JRh+CK0Jhi/L3/A+FeMDELzRgWHlP4JEvFwpP72abR9niy+ugOcwqxj2F93YyUGILUvoyJL+MozhL+NTi/PGvIl9qkuNIX/IeSFpV4v/Jay8KihiL8Rtd6AMdHTDrygSTG1tw2sWRxMI4SPYwY3yalFbfgyiSbqNhmtP5ckfjAAFxiDOPVpmMWEGZaQ2mZUWqRYGtFBJla6RmTK+bWcmeiFF+L+c414FGNw0sfFK+SRnvcc3RlCuoWKXDOg=
