changesetBaseRefs:
  - master

nodeLinker: pnp

npmAuthToken: acbb7760-ba02-4ee7-8dee-7211ec807b78

packageExtensions:
  "@devexpress/dx-chart-core@*":
    dependencies:
      "@devexpress/dx-core": "<=2.7.1"
  "@seine/content@*":
    dependencies:
      "@devexpress/dx-react-chart": "<=2.7.1"
      "@devexpress/dx-react-chart-material-ui": "<=2.7.1"
      "@material-ui/core": "*"
      "@material-ui/styles": "*"
      core-js: "*"
      draft-js: "*"
      react: "*"
      rollup: "*"
      styled-components: "*"
  "@seine/core@*":
    dependencies:
      core-js: "*"
      rollup: "*"
  "@seine/editor@*":
    dependencies:
      "@devexpress/dx-chart-core": "<=2.7.1"
      "@devexpress/dx-react-chart": "<=2.7.1"
      "@material-ui/core": "*"
      "@material-ui/icons": "*"
      "@material-ui/styles": "*"
      core-js: "*"
      draft-js: "*"
      react: "*"
      rollup: "*"
      styled-components: "*"
  "@seine/styles@*":
    dependencies:
      "@material-ui/core": "*"
      "@material-ui/styles": "*"
      "@material-ui/system": "*"
      core-js: "*"
      react: "*"
      rollup: "*"
      styled-components: "*"
  debug@*:
    dependencies:
      supports-color: ^7.2.0
  node-fetch@*:
    dependencies:
      encoding: ^0.1
  react-docgen-typescript-loader@*:
    dependencies:
      webpack: "*"
  "@storybook/core@*":
    dependencies:
      typescript: "*"
  "@storybook/react@*":
    dependencies:
      typescript: "*"
  "@storybook/addon-actions@*":
    dependencies:
      react: "*"
      react-dom: "*"
  react-color.macro@*:
    dependencies:
      react: "*"
      react-color: "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  seine-storybook@*:
    dependencies:
      webpack: "*"
      babel-loader: "*"
      core-js: "*"
  "uuid@*":
    dependencies:
      crypto: "*"
  styled-components@*:
    dependencies:
      react-is: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.3.2.cjs
