changesetBaseRefs: latest

nodeLinker: node-modules

npmAuthToken: acbb7760-ba02-4ee7-8dee-7211ec807b78

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.2.2.cjs
