changesetBaseRefs:
  - master

nodeLinker: pnp

npmAuthToken: acbb7760-ba02-4ee7-8dee-7211ec807b78

packageExtensions:
  "@devexpress/dx-chart-core@*":
    dependencies:
      "@devexpress/dx-core": "*"
  debug@*:
    dependencies:
      supports-color: ^7.2.0
  react-docgen-typescript-loader@*:
    dependencies:
      webpack: "*"
  "@storybook/core@*":
    dependencies:
      typescript: "*"
  "@storybook/react@*":
    dependencies:
      typescript: "*"
  "@storybook/addon-actions@*":
    dependencies:
      react: "*"
      react-dom: "*"
  react-color.macro@*:
    dependencies:
      react: "*"
      react-color: "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  "uuid@*":
    dependencies:
      crypto: "*"
  styled-components@*:
    dependencies:
      react-is: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.3.2.cjs
