nodeLinker: pnp

npmAuthToken: acbb7760-ba02-4ee7-8dee-7211ec807b78

packageExtensions:
  debug@*:
    dependencies:
      supports-color: "^7.2.0"

  node-fetch@*:
    dependencies:
      encoding: "^0.1"

  seine@*:
    dependencies:
      core-js: "*"

  '@seine/core@*':
    dependencies:
      core-js: "*"

  '@seine/content@*':
    dependencies:
      "@devexpress/dx-react-chart": "^2.7.0"
      "@devexpress/dx-react-chart-material-ui": "^2.7.0"
      "@material-ui/core": "4.9"
      "@storybook/addon-actions": "^6.0.21"
      core-js: "*"
      draft-js: "^0.11.0"
      react: "^16.9.0"
      styled-components: "^4.3.2"


  '@seine/editor@*':
    dependencies:
      "@devexpress/dx-react-chart": "^2.7.0"
      "@material-ui/core": "4.9"
      "@material-ui/icons": "4.9"
      core-js: "*"
      draft-js: "^0.11.0"
      react: "^16.9.0"
      styled-components: "^4.3.2"

  '@seine/styles@*':
    dependencies:
      core-js: "*"
      react: "^16.9.0"
      styled-components: "^4.3.2"

  '@seine/ui@*':
    dependencies:
      styled-components: "^4.3.2"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpMode: loose

yarnPath: .yarn/releases/yarn-2.2.2.cjs
