changesetBaseRefs: master

nodeLinker: pnp

npmAuthToken: acbb7760-ba02-4ee7-8dee-7211ec807b78

packageExtensions:
  "@devexpress/dx-chart-core@*":
    dependencies:
      "@devexpress/dx-core": "*"
  "@seine/content@*":
    dependencies:
      "@devexpress/dx-react-chart": "*"
      "@devexpress/dx-react-chart-material-ui": "*"
      "@material-ui/core": 4.9
      core-js: "*"
      draft-js: ^0.11.0
      react: ^16.9.0
      rollup: "*"
      styled-components: ^4.3.2
  "@seine/core@*":
    dependencies:
      core-js: "*"
      rollup: "*"
  "@seine/editor@*":
    dependencies:
      "@devexpress/dx-react-chart": "*"
      "@material-ui/core": "*"
      "@material-ui/icons": "*"
      core-js: "*"
      draft-js: ^0.11.0
      react: ^16.9.0
      rollup: "*"
      styled-components: ^4.3.2
  "@seine/styles@*":
    dependencies:
      core-js: "*"
      react: ^16.9.0
      rollup: "*"
      styled-components: ^4.3.2
  debug@*:
    dependencies:
      supports-color: ^7.2.0
  node-fetch@*:
    dependencies:
      encoding: ^0.1
  react-docgen-typescript-loader@*:
    dependencies:
      webpack: "*"
  "@storybook/core@*":
    dependencies:
      typescript: "*"
  "@storybook/react@*":
    dependencies:
      typescript: "*"
  "@storybook/addon-actions@*":
    dependencies:
      react: "*"
      react-dom: "*"
  "eslint-config-react-app@*":
    dependencies:
      eslint: "*"
      "@typescript-eslint/eslint-plugin": "*"
      "@typescript-eslint/parser": "2"
      "eslint-plugin-flowtype": "5.2"
      "eslint-plugin-react-hooks": "*"
  react-color.macro@*:
    dependencies:
      react: "*"
      react-color: "*"
  react-dev-utils@*:
    dependencies:
      typescript: "*"
      webpack: "*"
  seine-storybook@*:
    dependencies:
      webpack: "*"
      babel-loader: "*"
      core-js: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.3.2.cjs
