changesetBaseRefs:
  - master

nodeLinker: pnp

npmAuthToken: acbb7760-ba02-4ee7-8dee-7211ec807b78

packageExtensions:
  '@devexpress/dx-chart-core@*':
    dependencies:
      '@devexpress/dx-core': '*'
  '@mdx-js/loader@*':
    dependencies:
      react: '*'
  '@storybook/addon-storyshots@*':
    dependencies:
      jest: '*'
  '@storybook/core@*':
    dependencies:
      typescript: '*'
  '@storybook/react@*':
    dependencies:
      typescript: '*'
  'eslint-plugin-prettier@*':
    dependencies:
      eslint-config-prettier: '*'
  react-dev-utils@*:
    dependencies:
      typescript: '*'
      webpack: '*'
  react-docgen-typescript-loader@*:
    dependencies:
      webpack: '*'
  styled-components@*:
    dependencies:
      react-is: '*'
  '@cypress/webpack-preprocessor@*':
    dependencies:
      '@babel/preset-env': '*'
    peerDependencies:
      'webpack': '5.x'
  cypress-image-snapshot@*:
    dependencies:
      jest: '*'
    peerDependencies:
      cypress: '6.x'
  cypress-storybook@*:
    dependencies:
      '@storybook/react': '*'
      '@babel/core': '*'
      react-dom: '*'
      react: '*'
  seine-storybook@*:
    dependencies:
      react: '*'
      react-dom: '*'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: '@yarnpkg/plugin-version'
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: '@yarnpkg/plugin-workspace-tools'

yarnPath: .yarn/releases/yarn-2.4.0.cjs
